/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Add (void);
GtkWidget* create_Display (void);
GtkWidget* create_Remove (void);
GtkWidget* create_Edit (void);
GtkWidget* create_Confirmation (void);
GtkWidget* create_Delete_confirmation (void);
GtkWidget* create_Tache_supplementaire_ (void);
GtkWidget* create_Success (void);
GtkWidget* create_Echec (void);
GtkWidget* create_Gender (void);
GtkWidget* create_successfull_deletion (void);
GtkWidget* create_Agent_not_found (void);
GtkWidget* create_Research (void);
GtkWidget* create_admincitoyen (void);
GtkWidget* create_gerer (void);
