/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Add (void)
{
  GtkWidget *Add;
  GtkWidget *fixed1;
  GtkWidget *entryPhoneNumber;
  GtkWidget *entryadress;
  GtkWidget *entryFirstName;
  GtkWidget *entryLastName;
  GtkWidget *entryNIC;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *NICadd;
  GtkWidget *First_Name_add;
  GtkWidget *Last_Name_add;
  GtkWidget *Adressadd;
  GtkWidget *Genderadd;
  GtkWidget *CancelAdd;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image25;
  GtkWidget *label63;
  GtkWidget *labelresultat;
  GtkWidget *Phone_number_add;
  GtkWidget *Dayadd;
  GtkWidget *Yearadd;
  GtkWidget *Monthadd;
  GtkWidget *SaveAdd;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image24;
  GtkWidget *label62;
  GtkWidget *Contract_Type;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *Permanent;
  GtkWidget *Part_Time;
  GtkWidget *radiobutton2;
  GtkWidget *label9;
  GtkWidget *workspaceadd;
  GtkWidget *dateadd;
  GtkWidget *retour1;
  GtkWidget *image40;
  GtkWidget *image50;
  GtkWidget *Full_Time;
  GtkWidget *combo_entry5;
  GtkWidget *Temporary_Seasonal;
  GtkWidget *label99;

  Add = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Add), _("Add"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Add), fixed1);
  gtk_container_set_border_width (GTK_CONTAINER (fixed1), 2);

  entryPhoneNumber = gtk_entry_new ();
  gtk_widget_show (entryPhoneNumber);
  gtk_fixed_put (GTK_FIXED (fixed1), entryPhoneNumber, 128, 240);
  gtk_widget_set_size_request (entryPhoneNumber, 178, 31);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPhoneNumber), 8226);

  entryadress = gtk_entry_new ();
  gtk_widget_show (entryadress);
  gtk_fixed_put (GTK_FIXED (fixed1), entryadress, 130, 288);
  gtk_widget_set_size_request (entryadress, 172, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryadress), 8226);

  entryFirstName = gtk_entry_new ();
  gtk_widget_show (entryFirstName);
  gtk_fixed_put (GTK_FIXED (fixed1), entryFirstName, 128, 152);
  gtk_widget_set_size_request (entryFirstName, 174, 31);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryFirstName), 8226);

  entryLastName = gtk_entry_new ();
  gtk_widget_show (entryLastName);
  gtk_fixed_put (GTK_FIXED (fixed1), entryLastName, 128, 192);
  gtk_widget_set_size_request (entryLastName, 174, 31);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryLastName), 8226);

  entryNIC = gtk_entry_new ();
  gtk_widget_show (entryNIC);
  gtk_fixed_put (GTK_FIXED (fixed1), entryNIC, 128, 104);
  gtk_widget_set_size_request (entryNIC, 170, 31);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNIC), 8226);

  spinbutton2_adj = gtk_adjustment_new (1, 1930, 2006, 1, 10, 0);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton2, 666, 144);
  gtk_widget_set_size_request (spinbutton2, 62, 31);

  spinbutton3_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 0);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton3, 576, 144);
  gtk_widget_set_size_request (spinbutton3, 46, 31);

  spinbutton4_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 0);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton4, 480, 144);
  gtk_widget_set_size_request (spinbutton4, 46, 29);

  NICadd = gtk_label_new (_("NIC :"));
  gtk_widget_show (NICadd);
  gtk_fixed_put (GTK_FIXED (fixed1), NICadd, 64, 104);
  gtk_widget_set_size_request (NICadd, 52, 29);

  First_Name_add = gtk_label_new (_("First Name:"));
  gtk_widget_show (First_Name_add);
  gtk_fixed_put (GTK_FIXED (fixed1), First_Name_add, 24, 152);
  gtk_widget_set_size_request (First_Name_add, 86, 27);

  Last_Name_add = gtk_label_new (_("Last Name :"));
  gtk_widget_show (Last_Name_add);
  gtk_fixed_put (GTK_FIXED (fixed1), Last_Name_add, 24, 200);
  gtk_widget_set_size_request (Last_Name_add, 80, 25);

  Adressadd = gtk_label_new (_("Adress :"));
  gtk_widget_show (Adressadd);
  gtk_fixed_put (GTK_FIXED (fixed1), Adressadd, 40, 288);
  gtk_widget_set_size_request (Adressadd, 74, 35);

  Genderadd = gtk_label_new (_("Gender :"));
  gtk_widget_show (Genderadd);
  gtk_fixed_put (GTK_FIXED (fixed1), Genderadd, 40, 344);
  gtk_widget_set_size_request (Genderadd, 64, 45);
  gtk_misc_set_padding (GTK_MISC (Genderadd), 6, 0);

  CancelAdd = gtk_button_new ();
  gtk_widget_show (CancelAdd);
  gtk_fixed_put (GTK_FIXED (fixed1), CancelAdd, 218, 464);
  gtk_widget_set_size_request (CancelAdd, 86, 33);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (CancelAdd), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image25 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox7), image25, FALSE, FALSE, 0);

  label63 = gtk_label_new_with_mnemonic (_("Cancel\n"));
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox7), label63, FALSE, FALSE, 0);

  labelresultat = gtk_label_new ("");
  gtk_widget_show (labelresultat);
  gtk_fixed_put (GTK_FIXED (fixed1), labelresultat, 8, 424);
  gtk_widget_set_size_request (labelresultat, 718, 26);
  gtk_misc_set_alignment (GTK_MISC (labelresultat), 0.59, 0.5);

  Phone_number_add = gtk_label_new (_("Phone number :"));
  gtk_widget_show (Phone_number_add);
  gtk_fixed_put (GTK_FIXED (fixed1), Phone_number_add, 0, 240);
  gtk_widget_set_size_request (Phone_number_add, 110, 34);

  Dayadd = gtk_label_new (_("Day:"));
  gtk_widget_show (Dayadd);
  gtk_fixed_put (GTK_FIXED (fixed1), Dayadd, 432, 144);
  gtk_widget_set_size_request (Dayadd, 46, 27);

  Yearadd = gtk_label_new (_("Year:"));
  gtk_widget_show (Yearadd);
  gtk_fixed_put (GTK_FIXED (fixed1), Yearadd, 616, 144);
  gtk_widget_set_size_request (Yearadd, 56, 29);

  Monthadd = gtk_label_new (_("Month:"));
  gtk_widget_show (Monthadd);
  gtk_fixed_put (GTK_FIXED (fixed1), Monthadd, 528, 144);
  gtk_widget_set_size_request (Monthadd, 46, 26);

  SaveAdd = gtk_button_new ();
  gtk_widget_show (SaveAdd);
  gtk_fixed_put (GTK_FIXED (fixed1), SaveAdd, 448, 464);
  gtk_widget_set_size_request (SaveAdd, 94, 33);
  gtk_button_set_focus_on_click (GTK_BUTTON (SaveAdd), FALSE);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (SaveAdd), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image24 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox6), image24, FALSE, FALSE, 0);

  label62 = gtk_label_new_with_mnemonic (_("Save\n"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox6), label62, FALSE, FALSE, 0);

  Contract_Type = gtk_label_new (_("Contract Type:"));
  gtk_widget_show (Contract_Type);
  gtk_fixed_put (GTK_FIXED (fixed1), Contract_Type, 328, 200);
  gtk_widget_set_size_request (Contract_Type, 102, 19);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Male"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton1, 128, 352);
  gtk_widget_set_size_request (radiobutton1, 92, 36);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  Permanent = gtk_check_button_new_with_mnemonic (_("Permanent"));
  gtk_widget_show (Permanent);
  gtk_fixed_put (GTK_FIXED (fixed1), Permanent, 480, 360);
  gtk_widget_set_size_request (Permanent, 118, 24);

  Part_Time = gtk_check_button_new_with_mnemonic (_("Part-Time"));
  gtk_widget_show (Part_Time);
  gtk_fixed_put (GTK_FIXED (fixed1), Part_Time, 480, 256);
  gtk_widget_set_size_request (Part_Time, 118, 24);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Female"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton2, 232, 352);
  gtk_widget_set_size_request (radiobutton2, 86, 38);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  label9 = gtk_label_new (_("Adding a new Agent :"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 0, 56);
  gtk_widget_set_size_request (label9, 192, 25);

  workspaceadd = gtk_label_new (_("Workspace :"));
  gtk_widget_show (workspaceadd);
  gtk_fixed_put (GTK_FIXED (fixed1), workspaceadd, 320, 96);
  gtk_widget_set_size_request (workspaceadd, 134, 27);

  dateadd = gtk_label_new (_("Date of birth :\n"));
  gtk_widget_show (dateadd);
  gtk_fixed_put (GTK_FIXED (fixed1), dateadd, 312, 152);
  gtk_widget_set_size_request (dateadd, 142, 35);

  retour1 = gtk_button_new ();
  gtk_widget_show (retour1);
  gtk_fixed_put (GTK_FIXED (fixed1), retour1, 24, 8);
  gtk_widget_set_size_request (retour1, 38, 31);

  image40 = gtk_image_new_from_stock ("gtk-select-all", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image40);
  gtk_container_add (GTK_CONTAINER (retour1), image40);

  image50 = create_pixmap (Add, "park&go.png");
  gtk_widget_show (image50);
  gtk_fixed_put (GTK_FIXED (fixed1), image50, 608, 0);
  gtk_widget_set_size_request (image50, 124, 82);
  gtk_misc_set_alignment (GTK_MISC (image50), 0.2, 0.5);

  Full_Time = gtk_check_button_new_with_mnemonic (_("Full-Time"));
  gtk_widget_show (Full_Time);
  gtk_fixed_put (GTK_FIXED (fixed1), Full_Time, 480, 200);
  gtk_widget_set_size_request (Full_Time, 118, 24);

  combo_entry5 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo_entry5);
  gtk_fixed_put (GTK_FIXED (fixed1), combo_entry5, 480, 96);
  gtk_widget_set_size_request (combo_entry5, 222, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_entry5), _("Parking1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_entry5), _("Parking2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_entry5), _("Parking3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_entry5), _("Parking4"));

  Temporary_Seasonal = gtk_check_button_new_with_mnemonic (_("Temporary/Seasonal"));
  gtk_widget_show (Temporary_Seasonal);
  gtk_fixed_put (GTK_FIXED (fixed1), Temporary_Seasonal, 480, 304);
  gtk_widget_set_size_request (Temporary_Seasonal, 182, 26);

  label99 = gtk_label_new ("");
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed1), label99, 184, 408);
  gtk_widget_set_size_request (label99, 374, 29);

  g_signal_connect ((gpointer) CancelAdd, "clicked",
                    G_CALLBACK (on_CancelAdd_clicked),
                    NULL);
  g_signal_connect ((gpointer) SaveAdd, "clicked",
                    G_CALLBACK (on_SaveAdd_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) Permanent, "toggled",
                    G_CALLBACK (on_Permanent_toggled),
                    NULL);
  g_signal_connect ((gpointer) Part_Time, "toggled",
                    G_CALLBACK (on_Part_Time_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) retour1, "clicked",
                    G_CALLBACK (on_retour1_clicked),
                    NULL);
  g_signal_connect ((gpointer) Full_Time, "toggled",
                    G_CALLBACK (on_Full_Time_toggled),
                    NULL);
  g_signal_connect ((gpointer) Temporary_Seasonal, "toggled",
                    G_CALLBACK (on_Temporary_Seasonal_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Add, Add, "Add");
  GLADE_HOOKUP_OBJECT (Add, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Add, entryPhoneNumber, "entryPhoneNumber");
  GLADE_HOOKUP_OBJECT (Add, entryadress, "entryadress");
  GLADE_HOOKUP_OBJECT (Add, entryFirstName, "entryFirstName");
  GLADE_HOOKUP_OBJECT (Add, entryLastName, "entryLastName");
  GLADE_HOOKUP_OBJECT (Add, entryNIC, "entryNIC");
  GLADE_HOOKUP_OBJECT (Add, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (Add, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (Add, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (Add, NICadd, "NICadd");
  GLADE_HOOKUP_OBJECT (Add, First_Name_add, "First_Name_add");
  GLADE_HOOKUP_OBJECT (Add, Last_Name_add, "Last_Name_add");
  GLADE_HOOKUP_OBJECT (Add, Adressadd, "Adressadd");
  GLADE_HOOKUP_OBJECT (Add, Genderadd, "Genderadd");
  GLADE_HOOKUP_OBJECT (Add, CancelAdd, "CancelAdd");
  GLADE_HOOKUP_OBJECT (Add, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Add, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Add, image25, "image25");
  GLADE_HOOKUP_OBJECT (Add, label63, "label63");
  GLADE_HOOKUP_OBJECT (Add, labelresultat, "labelresultat");
  GLADE_HOOKUP_OBJECT (Add, Phone_number_add, "Phone_number_add");
  GLADE_HOOKUP_OBJECT (Add, Dayadd, "Dayadd");
  GLADE_HOOKUP_OBJECT (Add, Yearadd, "Yearadd");
  GLADE_HOOKUP_OBJECT (Add, Monthadd, "Monthadd");
  GLADE_HOOKUP_OBJECT (Add, SaveAdd, "SaveAdd");
  GLADE_HOOKUP_OBJECT (Add, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Add, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Add, image24, "image24");
  GLADE_HOOKUP_OBJECT (Add, label62, "label62");
  GLADE_HOOKUP_OBJECT (Add, Contract_Type, "Contract_Type");
  GLADE_HOOKUP_OBJECT (Add, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (Add, Permanent, "Permanent");
  GLADE_HOOKUP_OBJECT (Add, Part_Time, "Part_Time");
  GLADE_HOOKUP_OBJECT (Add, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (Add, label9, "label9");
  GLADE_HOOKUP_OBJECT (Add, workspaceadd, "workspaceadd");
  GLADE_HOOKUP_OBJECT (Add, dateadd, "dateadd");
  GLADE_HOOKUP_OBJECT (Add, retour1, "retour1");
  GLADE_HOOKUP_OBJECT (Add, image40, "image40");
  GLADE_HOOKUP_OBJECT (Add, image50, "image50");
  GLADE_HOOKUP_OBJECT (Add, Full_Time, "Full_Time");
  GLADE_HOOKUP_OBJECT (Add, combo_entry5, "combo_entry5");
  GLADE_HOOKUP_OBJECT (Add, Temporary_Seasonal, "Temporary_Seasonal");
  GLADE_HOOKUP_OBJECT (Add, label99, "label99");

  return Add;
}

GtkWidget*
create_Display (void)
{
  GtkWidget *Display;
  GtkWidget *fixed4;
  GtkWidget *treeview1;
  GtkWidget *image49;
  GtkWidget *Adddisplay;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image18;
  GtkWidget *label57;
  GtkWidget *Reservation;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image44;
  GtkWidget *label72;
  GtkWidget *Deletedisplay;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image20;
  GtkWidget *label59;
  GtkWidget *researchID;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image62;
  GtkWidget *label87;
  GtkWidget *Editdisplay;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image19;
  GtkWidget *label58;
  GtkWidget *Canceldisplay;
  GtkWidget *image43;
  GtkWidget *label88;
  GtkWidget *research;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image59;
  GtkWidget *label81;
  GtkWidget *label89;
  GtkWidget *label13;
  GtkWidget *button4;
  GtkWidget *image63;

  Display = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Display), _("Display"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Display), fixed4);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview1, 16, 256);
  gtk_widget_set_size_request (treeview1, 496, 200);

  image49 = create_pixmap (Display, "Capture du 2024-10-25 14-28-22.png");
  gtk_widget_show (image49);
  gtk_fixed_put (GTK_FIXED (fixed4), image49, 0, 0);
  gtk_widget_set_size_request (image49, 528, 136);

  Adddisplay = gtk_button_new ();
  gtk_widget_show (Adddisplay);
  gtk_fixed_put (GTK_FIXED (fixed4), Adddisplay, 16, 496);
  gtk_widget_set_size_request (Adddisplay, 80, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (Adddisplay), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image18 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox3), image18, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("Add"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox3), label57, FALSE, FALSE, 0);

  Reservation = gtk_button_new ();
  gtk_widget_show (Reservation);
  gtk_fixed_put (GTK_FIXED (fixed4), Reservation, 392, 496);
  gtk_widget_set_size_request (Reservation, 112, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (Reservation), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image44 = gtk_image_new_from_stock ("gtk-file", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image44);
  gtk_box_pack_start (GTK_BOX (hbox14), image44, FALSE, FALSE, 0);

  label72 = gtk_label_new_with_mnemonic (_("Reservation"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox14), label72, FALSE, FALSE, 0);

  Deletedisplay = gtk_button_new ();
  gtk_widget_show (Deletedisplay);
  gtk_fixed_put (GTK_FIXED (fixed4), Deletedisplay, 192, 496);
  gtk_widget_set_size_request (Deletedisplay, 80, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (Deletedisplay), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image20 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox5), image20, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("Delete"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox5), label59, FALSE, FALSE, 0);

  researchID = gtk_button_new ();
  gtk_widget_show (researchID);
  gtk_fixed_put (GTK_FIXED (fixed4), researchID, 288, 496);
  gtk_widget_set_size_request (researchID, 96, 29);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (researchID), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image62 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image62);
  gtk_box_pack_start (GTK_BOX (hbox20), image62, FALSE, FALSE, 0);

  label87 = gtk_label_new_with_mnemonic (_("Research"));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox20), label87, FALSE, FALSE, 0);

  Editdisplay = gtk_button_new ();
  gtk_widget_show (Editdisplay);
  gtk_fixed_put (GTK_FIXED (fixed4), Editdisplay, 112, 496);
  gtk_widget_set_size_request (Editdisplay, 72, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (Editdisplay), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image19 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox4), image19, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("Edit"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox4), label58, FALSE, FALSE, 0);

  Canceldisplay = gtk_button_new ();
  gtk_widget_show (Canceldisplay);
  gtk_fixed_put (GTK_FIXED (fixed4), Canceldisplay, 488, 144);
  gtk_widget_set_size_request (Canceldisplay, 32, 32);

  image43 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image43);
  gtk_container_add (GTK_CONTAINER (Canceldisplay), image43);

  label88 = gtk_label_new (_("Welcome to the Agent management section :"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed4), label88, 88, 136);
  gtk_widget_set_size_request (label88, 336, 33);

  research = gtk_button_new ();
  gtk_widget_show (research);
  gtk_fixed_put (GTK_FIXED (fixed4), research, 336, 216);
  gtk_widget_set_size_request (research, 96, 29);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (research), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image59 = gtk_image_new_from_stock ("gtk-indent", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image59);
  gtk_box_pack_start (GTK_BOX (hbox18), image59, FALSE, FALSE, 0);

  label81 = gtk_label_new_with_mnemonic (_("Diplay"));
  gtk_widget_show (label81);
  gtk_box_pack_start (GTK_BOX (hbox18), label81, FALSE, FALSE, 0);

  label89 = gtk_label_new ("");
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed4), label89, 472, 528);
  gtk_widget_set_size_request (label89, 49, 17);

  label13 = gtk_label_new (_("Display all parking agents:"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed4), label13, 8, 200);
  gtk_widget_set_size_request (label13, 248, 49);
  gtk_label_set_justify (GTK_LABEL (label13), GTK_JUSTIFY_FILL);
  gtk_misc_set_alignment (GTK_MISC (label13), 0.24, 0.5);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed4), button4, 8, 144);
  gtk_widget_set_size_request (button4, 32, 32);

  image63 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image63);
  gtk_container_add (GTK_CONTAINER (button4), image63);

  g_signal_connect ((gpointer) Adddisplay, "clicked",
                    G_CALLBACK (on_Adddisplay_clicked),
                    NULL);
  g_signal_connect ((gpointer) Reservation, "clicked",
                    G_CALLBACK (on_Reservation_clicked),
                    NULL);
  g_signal_connect ((gpointer) Deletedisplay, "clicked",
                    G_CALLBACK (on_Deletedisplay_clicked),
                    NULL);
  g_signal_connect ((gpointer) researchID, "clicked",
                    G_CALLBACK (on_researchID_clicked),
                    NULL);
  g_signal_connect ((gpointer) Editdisplay, "clicked",
                    G_CALLBACK (on_Editdisplay_clicked),
                    NULL);
  g_signal_connect ((gpointer) Canceldisplay, "clicked",
                    G_CALLBACK (on_Canceldisplay_clicked),
                    NULL);
  g_signal_connect ((gpointer) research, "clicked",
                    G_CALLBACK (on_research_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Display, Display, "Display");
  GLADE_HOOKUP_OBJECT (Display, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Display, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Display, image49, "image49");
  GLADE_HOOKUP_OBJECT (Display, Adddisplay, "Adddisplay");
  GLADE_HOOKUP_OBJECT (Display, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Display, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Display, image18, "image18");
  GLADE_HOOKUP_OBJECT (Display, label57, "label57");
  GLADE_HOOKUP_OBJECT (Display, Reservation, "Reservation");
  GLADE_HOOKUP_OBJECT (Display, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Display, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Display, image44, "image44");
  GLADE_HOOKUP_OBJECT (Display, label72, "label72");
  GLADE_HOOKUP_OBJECT (Display, Deletedisplay, "Deletedisplay");
  GLADE_HOOKUP_OBJECT (Display, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Display, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Display, image20, "image20");
  GLADE_HOOKUP_OBJECT (Display, label59, "label59");
  GLADE_HOOKUP_OBJECT (Display, researchID, "researchID");
  GLADE_HOOKUP_OBJECT (Display, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (Display, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (Display, image62, "image62");
  GLADE_HOOKUP_OBJECT (Display, label87, "label87");
  GLADE_HOOKUP_OBJECT (Display, Editdisplay, "Editdisplay");
  GLADE_HOOKUP_OBJECT (Display, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Display, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Display, image19, "image19");
  GLADE_HOOKUP_OBJECT (Display, label58, "label58");
  GLADE_HOOKUP_OBJECT (Display, Canceldisplay, "Canceldisplay");
  GLADE_HOOKUP_OBJECT (Display, image43, "image43");
  GLADE_HOOKUP_OBJECT (Display, label88, "label88");
  GLADE_HOOKUP_OBJECT (Display, research, "research");
  GLADE_HOOKUP_OBJECT (Display, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (Display, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Display, image59, "image59");
  GLADE_HOOKUP_OBJECT (Display, label81, "label81");
  GLADE_HOOKUP_OBJECT (Display, label89, "label89");
  GLADE_HOOKUP_OBJECT (Display, label13, "label13");
  GLADE_HOOKUP_OBJECT (Display, button4, "button4");
  GLADE_HOOKUP_OBJECT (Display, image63, "image63");

  return Display;
}

GtkWidget*
create_Remove (void)
{
  GtkWidget *Remove;
  GtkWidget *fixed5;
  GtkWidget *ID_entry;
  GtkWidget *retour3;
  GtkWidget *image42;
  GtkWidget *label21;
  GtkWidget *Delete;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image38;
  GtkWidget *label71;
  GtkWidget *image51;
  GtkWidget *label98;
  GtkWidget *label12;

  Remove = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Remove), _("Remove"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Remove), fixed5);

  ID_entry = gtk_entry_new ();
  gtk_widget_show (ID_entry);
  gtk_fixed_put (GTK_FIXED (fixed5), ID_entry, 160, 144);
  gtk_widget_set_size_request (ID_entry, 224, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (ID_entry), 8226);

  retour3 = gtk_button_new ();
  gtk_widget_show (retour3);
  gtk_fixed_put (GTK_FIXED (fixed5), retour3, 8, 8);
  gtk_widget_set_size_request (retour3, 40, 29);

  image42 = gtk_image_new_from_stock ("gtk-select-all", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image42);
  gtk_container_add (GTK_CONTAINER (retour3), image42);

  label21 = gtk_label_new (_("Identifier :"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed5), label21, 48, 144);
  gtk_widget_set_size_request (label21, 128, 33);

  Delete = gtk_button_new ();
  gtk_widget_show (Delete);
  gtk_fixed_put (GTK_FIXED (fixed5), Delete, 200, 224);
  gtk_widget_set_size_request (Delete, 136, 37);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (Delete), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image38 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image38);
  gtk_box_pack_start (GTK_BOX (hbox13), image38, FALSE, FALSE, 0);

  label71 = gtk_label_new_with_mnemonic (_("Delete"));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox13), label71, FALSE, FALSE, 0);

  image51 = create_pixmap (Remove, "park&go.png");
  gtk_widget_show (image51);
  gtk_fixed_put (GTK_FIXED (fixed5), image51, 376, 0);
  gtk_widget_set_size_request (image51, 125, 85);
  gtk_misc_set_alignment (GTK_MISC (image51), 0.2, 0.5);

  label98 = gtk_label_new ("");
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed5), label98, 368, 264);
  gtk_widget_set_size_request (label98, 49, 17);

  label12 = gtk_label_new (_("Delete an agent :"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed5), label12, 8, 48);
  gtk_widget_set_size_request (label12, 184, 57);

  g_signal_connect ((gpointer) retour3, "clicked",
                    G_CALLBACK (on_retour3_clicked),
                    NULL);
  g_signal_connect ((gpointer) Delete, "clicked",
                    G_CALLBACK (on_Delete_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Remove, Remove, "Remove");
  GLADE_HOOKUP_OBJECT (Remove, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Remove, ID_entry, "ID_entry");
  GLADE_HOOKUP_OBJECT (Remove, retour3, "retour3");
  GLADE_HOOKUP_OBJECT (Remove, image42, "image42");
  GLADE_HOOKUP_OBJECT (Remove, label21, "label21");
  GLADE_HOOKUP_OBJECT (Remove, Delete, "Delete");
  GLADE_HOOKUP_OBJECT (Remove, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Remove, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Remove, image38, "image38");
  GLADE_HOOKUP_OBJECT (Remove, label71, "label71");
  GLADE_HOOKUP_OBJECT (Remove, image51, "image51");
  GLADE_HOOKUP_OBJECT (Remove, label98, "label98");
  GLADE_HOOKUP_OBJECT (Remove, label12, "label12");

  return Remove;
}

GtkWidget*
create_Edit (void)
{
  GtkWidget *Edit;
  GtkWidget *fixed6;
  GtkWidget *entryNIC;
  GtkWidget *entryAdress;
  GtkWidget *entryFirstName;
  GtkWidget *entryPhoneNumber;
  GtkWidget *entryLastName;
  GtkWidget *label20;
  GtkWidget *label14;
  GtkWidget *label17;
  GtkWidget *label16;
  GtkWidget *label15;
  GtkWidget *label19;
  GtkWidget *label18;
  GtkWidget *label68;
  GtkWidget *label39;
  GtkWidget *label46;
  GtkObject *spinbuttonDay_adj;
  GtkWidget *spinbuttonDay;
  GtkObject *spinbuttonMonth_adj;
  GtkWidget *spinbuttonMonth;
  GtkObject *spinbuttonYear_adj;
  GtkWidget *spinbuttonYear;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkWidget *label49;
  GtkWidget *Editedit;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image35;
  GtkWidget *label70;
  GtkWidget *radiobuttonMale;
  GSList *radiobuttonMale_group = NULL;
  GtkWidget *retour2;
  GtkWidget *image41;
  GtkWidget *image52;
  GtkWidget *canceledit;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image34;
  GtkWidget *label69;
  GtkWidget *radiobuttonFemale;
  GtkWidget *checkbuttonFull_Time;
  GtkWidget *checkbuttonPart_Time;
  GtkWidget *checkbuttonTemporary;
  GtkWidget *checkbuttonPermanent;
  GtkWidget *comboboxentry2;
  GtkWidget *verifier;
  GtkWidget *image39;
  GtkWidget *label100;

  Edit = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Edit), _("Edit"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Edit), fixed6);

  entryNIC = gtk_entry_new ();
  gtk_widget_show (entryNIC);
  gtk_fixed_put (GTK_FIXED (fixed6), entryNIC, 136, 104);
  gtk_widget_set_size_request (entryNIC, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNIC), 8226);

  entryAdress = gtk_entry_new ();
  gtk_widget_show (entryAdress);
  gtk_fixed_put (GTK_FIXED (fixed6), entryAdress, 136, 296);
  gtk_widget_set_size_request (entryAdress, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryAdress), 8226);

  entryFirstName = gtk_entry_new ();
  gtk_widget_show (entryFirstName);
  gtk_fixed_put (GTK_FIXED (fixed6), entryFirstName, 136, 152);
  gtk_widget_set_size_request (entryFirstName, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryFirstName), 8226);

  entryPhoneNumber = gtk_entry_new ();
  gtk_widget_show (entryPhoneNumber);
  gtk_fixed_put (GTK_FIXED (fixed6), entryPhoneNumber, 136, 248);
  gtk_widget_set_size_request (entryPhoneNumber, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPhoneNumber), 8226);

  entryLastName = gtk_entry_new ();
  gtk_widget_show (entryLastName);
  gtk_fixed_put (GTK_FIXED (fixed6), entryLastName, 136, 200);
  gtk_widget_set_size_request (entryLastName, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryLastName), 8226);

  label20 = gtk_label_new (_("Edit agent information :"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed6), label20, 24, 40);
  gtk_widget_set_size_request (label20, 168, 41);

  label14 = gtk_label_new (_("First name  :"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed6), label14, 40, 152);
  gtk_widget_set_size_request (label14, 80, 25);

  label17 = gtk_label_new (_("Adress:"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed6), label17, 56, 296);
  gtk_widget_set_size_request (label17, 80, 25);

  label16 = gtk_label_new (_("Phone number :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed6), label16, 16, 248);
  gtk_widget_set_size_request (label16, 104, 32);

  label15 = gtk_label_new (_("Last name :"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed6), label15, 40, 200);
  gtk_widget_set_size_request (label15, 80, 25);

  label19 = gtk_label_new (_("Gender :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed6), label19, 56, 360);
  gtk_widget_set_size_request (label19, 64, 25);
  gtk_misc_set_padding (GTK_MISC (label19), 6, 0);

  label18 = gtk_label_new (_("Workspace :"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed6), label18, 320, 104);
  gtk_widget_set_size_request (label18, 120, 25);

  label68 = gtk_label_new (_("Contract type :"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed6), label68, 336, 208);
  gtk_widget_set_size_request (label68, 104, 25);

  label39 = gtk_label_new (_("NIC :"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed6), label39, 80, 104);
  gtk_widget_set_size_request (label39, 52, 29);

  label46 = gtk_label_new (_("Date of Birth :"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed6), label46, 320, 152);
  gtk_widget_set_size_request (label46, 120, 25);

  spinbuttonDay_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonDay = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonDay_adj), 1, 0);
  gtk_widget_show (spinbuttonDay);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonDay, 472, 152);
  gtk_widget_set_size_request (spinbuttonDay, 48, 27);

  spinbuttonMonth_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonMonth = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMonth_adj), 1, 0);
  gtk_widget_show (spinbuttonMonth);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonMonth, 576, 152);
  gtk_widget_set_size_request (spinbuttonMonth, 48, 27);

  spinbuttonYear_adj = gtk_adjustment_new (1, 1930, 2006, 1, 10, 10);
  spinbuttonYear = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonYear_adj), 1, 0);
  gtk_widget_show (spinbuttonYear);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonYear, 664, 152);
  gtk_widget_set_size_request (spinbuttonYear, 64, 27);

  label47 = gtk_label_new (_("Day:"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed6), label47, 432, 152);
  gtk_widget_set_size_request (label47, 48, 25);

  label48 = gtk_label_new (_("Month :"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed6), label48, 520, 152);
  gtk_widget_set_size_request (label48, 56, 25);

  label49 = gtk_label_new (_("Year :"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed6), label49, 616, 152);
  gtk_widget_set_size_request (label49, 56, 25);

  Editedit = gtk_button_new ();
  gtk_widget_show (Editedit);
  gtk_fixed_put (GTK_FIXED (fixed6), Editedit, 504, 448);
  gtk_widget_set_size_request (Editedit, 88, 37);
  gtk_button_set_focus_on_click (GTK_BUTTON (Editedit), FALSE);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (Editedit), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image35 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox12), image35, FALSE, FALSE, 0);

  label70 = gtk_label_new_with_mnemonic (_("Edit"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox12), label70, FALSE, FALSE, 0);

  radiobuttonMale = gtk_radio_button_new_with_mnemonic (NULL, _("Male"));
  gtk_widget_show (radiobuttonMale);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobuttonMale, 144, 360);
  gtk_widget_set_size_request (radiobuttonMale, 72, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonMale), radiobuttonMale_group);
  radiobuttonMale_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonMale));

  retour2 = gtk_button_new ();
  gtk_widget_show (retour2);
  gtk_fixed_put (GTK_FIXED (fixed6), retour2, 8, 8);
  gtk_widget_set_size_request (retour2, 32, 29);

  image41 = gtk_image_new_from_stock ("gtk-select-all", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image41);
  gtk_container_add (GTK_CONTAINER (retour2), image41);

  image52 = create_pixmap (Edit, "park&go.png");
  gtk_widget_show (image52);
  gtk_fixed_put (GTK_FIXED (fixed6), image52, 608, 8);
  gtk_widget_set_size_request (image52, 125, 72);
  gtk_misc_set_alignment (GTK_MISC (image52), 0.2, 0.5);

  canceledit = gtk_button_new ();
  gtk_widget_show (canceledit);
  gtk_fixed_put (GTK_FIXED (fixed6), canceledit, 200, 448);
  gtk_widget_set_size_request (canceledit, 88, 37);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (canceledit), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image34 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox11), image34, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("Cancel\n"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox11), label69, FALSE, FALSE, 0);

  radiobuttonFemale = gtk_radio_button_new_with_mnemonic (NULL, _("Female"));
  gtk_widget_show (radiobuttonFemale);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobuttonFemale, 224, 360);
  gtk_widget_set_size_request (radiobuttonFemale, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonFemale), radiobuttonMale_group);
  radiobuttonMale_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonFemale));

  checkbuttonFull_Time = gtk_check_button_new_with_mnemonic (_("Full-Time"));
  gtk_widget_show (checkbuttonFull_Time);
  gtk_fixed_put (GTK_FIXED (fixed6), checkbuttonFull_Time, 488, 208);
  gtk_widget_set_size_request (checkbuttonFull_Time, 184, 24);

  checkbuttonPart_Time = gtk_check_button_new_with_mnemonic (_("Part-Time"));
  gtk_widget_show (checkbuttonPart_Time);
  gtk_fixed_put (GTK_FIXED (fixed6), checkbuttonPart_Time, 488, 256);
  gtk_widget_set_size_request (checkbuttonPart_Time, 118, 24);

  checkbuttonTemporary = gtk_check_button_new_with_mnemonic (_("Temporary/seasonal"));
  gtk_widget_show (checkbuttonTemporary);
  gtk_fixed_put (GTK_FIXED (fixed6), checkbuttonTemporary, 488, 304);
  gtk_widget_set_size_request (checkbuttonTemporary, 168, 24);

  checkbuttonPermanent = gtk_check_button_new_with_mnemonic (_("Permanent"));
  gtk_widget_show (checkbuttonPermanent);
  gtk_fixed_put (GTK_FIXED (fixed6), checkbuttonPermanent, 488, 352);
  gtk_widget_set_size_request (checkbuttonPermanent, 118, 24);

  comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxentry2, 472, 104);
  gtk_widget_set_size_request (comboboxentry2, 232, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("Parking1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("Parking2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("Parking3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("Parking4"));

  verifier = gtk_button_new ();
  gtk_widget_show (verifier);
  gtk_fixed_put (GTK_FIXED (fixed6), verifier, 216, 48);
  gtk_widget_set_size_request (verifier, 32, 29);

  image39 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_container_add (GTK_CONTAINER (verifier), image39);

  label100 = gtk_label_new ("");
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed6), label100, 152, 400);
  gtk_widget_set_size_request (label100, 464, 33);

  g_signal_connect ((gpointer) Editedit, "clicked",
                    G_CALLBACK (on_Editedit_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonMale, "toggled",
                    G_CALLBACK (on_radiobuttonMale_toggled),
                    NULL);
  g_signal_connect ((gpointer) retour2, "clicked",
                    G_CALLBACK (on_retour2_clicked),
                    NULL);
  g_signal_connect ((gpointer) canceledit, "clicked",
                    G_CALLBACK (on_canceledit_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonFemale, "toggled",
                    G_CALLBACK (on_radiobuttonFemale_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonFull_Time, "toggled",
                    G_CALLBACK (on_checkbuttonFull_Time_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonPart_Time, "toggled",
                    G_CALLBACK (on_checkbuttonPart_Time_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonTemporary, "toggled",
                    G_CALLBACK (on_checkbuttonTemporary_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonPermanent, "toggled",
                    G_CALLBACK (on_checkbuttonPermanent_toggled),
                    NULL);
  g_signal_connect ((gpointer) verifier, "clicked",
                    G_CALLBACK (on_verifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Edit, Edit, "Edit");
  GLADE_HOOKUP_OBJECT (Edit, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Edit, entryNIC, "entryNIC");
  GLADE_HOOKUP_OBJECT (Edit, entryAdress, "entryAdress");
  GLADE_HOOKUP_OBJECT (Edit, entryFirstName, "entryFirstName");
  GLADE_HOOKUP_OBJECT (Edit, entryPhoneNumber, "entryPhoneNumber");
  GLADE_HOOKUP_OBJECT (Edit, entryLastName, "entryLastName");
  GLADE_HOOKUP_OBJECT (Edit, label20, "label20");
  GLADE_HOOKUP_OBJECT (Edit, label14, "label14");
  GLADE_HOOKUP_OBJECT (Edit, label17, "label17");
  GLADE_HOOKUP_OBJECT (Edit, label16, "label16");
  GLADE_HOOKUP_OBJECT (Edit, label15, "label15");
  GLADE_HOOKUP_OBJECT (Edit, label19, "label19");
  GLADE_HOOKUP_OBJECT (Edit, label18, "label18");
  GLADE_HOOKUP_OBJECT (Edit, label68, "label68");
  GLADE_HOOKUP_OBJECT (Edit, label39, "label39");
  GLADE_HOOKUP_OBJECT (Edit, label46, "label46");
  GLADE_HOOKUP_OBJECT (Edit, spinbuttonDay, "spinbuttonDay");
  GLADE_HOOKUP_OBJECT (Edit, spinbuttonMonth, "spinbuttonMonth");
  GLADE_HOOKUP_OBJECT (Edit, spinbuttonYear, "spinbuttonYear");
  GLADE_HOOKUP_OBJECT (Edit, label47, "label47");
  GLADE_HOOKUP_OBJECT (Edit, label48, "label48");
  GLADE_HOOKUP_OBJECT (Edit, label49, "label49");
  GLADE_HOOKUP_OBJECT (Edit, Editedit, "Editedit");
  GLADE_HOOKUP_OBJECT (Edit, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Edit, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Edit, image35, "image35");
  GLADE_HOOKUP_OBJECT (Edit, label70, "label70");
  GLADE_HOOKUP_OBJECT (Edit, radiobuttonMale, "radiobuttonMale");
  GLADE_HOOKUP_OBJECT (Edit, retour2, "retour2");
  GLADE_HOOKUP_OBJECT (Edit, image41, "image41");
  GLADE_HOOKUP_OBJECT (Edit, image52, "image52");
  GLADE_HOOKUP_OBJECT (Edit, canceledit, "canceledit");
  GLADE_HOOKUP_OBJECT (Edit, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Edit, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Edit, image34, "image34");
  GLADE_HOOKUP_OBJECT (Edit, label69, "label69");
  GLADE_HOOKUP_OBJECT (Edit, radiobuttonFemale, "radiobuttonFemale");
  GLADE_HOOKUP_OBJECT (Edit, checkbuttonFull_Time, "checkbuttonFull_Time");
  GLADE_HOOKUP_OBJECT (Edit, checkbuttonPart_Time, "checkbuttonPart_Time");
  GLADE_HOOKUP_OBJECT (Edit, checkbuttonTemporary, "checkbuttonTemporary");
  GLADE_HOOKUP_OBJECT (Edit, checkbuttonPermanent, "checkbuttonPermanent");
  GLADE_HOOKUP_OBJECT (Edit, comboboxentry2, "comboboxentry2");
  GLADE_HOOKUP_OBJECT (Edit, verifier, "verifier");
  GLADE_HOOKUP_OBJECT (Edit, image39, "image39");
  GLADE_HOOKUP_OBJECT (Edit, label100, "label100");

  return Edit;
}

GtkWidget*
create_Confirmation (void)
{
  GtkWidget *Confirmation;
  GtkWidget *fixed17;
  GtkWidget *label40;
  GtkWidget *no;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image32;
  GtkWidget *label66;
  GtkWidget *yes;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image31;
  GtkWidget *label65;
  GtkWidget *label92;

  Confirmation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Confirmation), _("Confirmation"));

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (Confirmation), fixed17);

  label40 = gtk_label_new (_("want to modify ?"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed17), label40, 96, 48);
  gtk_widget_set_size_request (label40, 160, 25);

  no = gtk_button_new ();
  gtk_widget_show (no);
  gtk_fixed_put (GTK_FIXED (fixed17), no, 224, 112);
  gtk_widget_set_size_request (no, 74, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (no), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image32 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox10), image32, FALSE, FALSE, 0);

  label66 = gtk_label_new_with_mnemonic (_("No"));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox10), label66, FALSE, FALSE, 0);

  yes = gtk_button_new ();
  gtk_widget_show (yes);
  gtk_fixed_put (GTK_FIXED (fixed17), yes, 64, 112);
  gtk_widget_set_size_request (yes, 74, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (yes), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image31 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox9), image31, FALSE, FALSE, 0);

  label65 = gtk_label_new_with_mnemonic (_("Yes"));
  gtk_widget_show (label65);
  gtk_box_pack_start (GTK_BOX (hbox9), label65, FALSE, FALSE, 0);

  label92 = gtk_label_new ("");
  gtk_widget_show (label92);
  gtk_fixed_put (GTK_FIXED (fixed17), label92, 312, 152);
  gtk_widget_set_size_request (label92, 49, 17);

  g_signal_connect ((gpointer) no, "clicked",
                    G_CALLBACK (on_no_clicked),
                    NULL);
  g_signal_connect ((gpointer) yes, "clicked",
                    G_CALLBACK (on_yes_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Confirmation, Confirmation, "Confirmation");
  GLADE_HOOKUP_OBJECT (Confirmation, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (Confirmation, label40, "label40");
  GLADE_HOOKUP_OBJECT (Confirmation, no, "no");
  GLADE_HOOKUP_OBJECT (Confirmation, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Confirmation, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Confirmation, image32, "image32");
  GLADE_HOOKUP_OBJECT (Confirmation, label66, "label66");
  GLADE_HOOKUP_OBJECT (Confirmation, yes, "yes");
  GLADE_HOOKUP_OBJECT (Confirmation, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Confirmation, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Confirmation, image31, "image31");
  GLADE_HOOKUP_OBJECT (Confirmation, label65, "label65");
  GLADE_HOOKUP_OBJECT (Confirmation, label92, "label92");

  return Confirmation;
}

GtkWidget*
create_Delete_confirmation (void)
{
  GtkWidget *Delete_confirmation;
  GtkWidget *confirmation;
  GtkWidget *image8;
  GtkWidget *label41;
  GtkWidget *confirm;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image47;
  GtkWidget *label74;
  GtkWidget *cancelconfirmation;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image46;
  GtkWidget *label73;
  GtkWidget *label90;

  Delete_confirmation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Delete_confirmation), _("Delete_confirmation"));

  confirmation = gtk_fixed_new ();
  gtk_widget_show (confirmation);
  gtk_container_add (GTK_CONTAINER (Delete_confirmation), confirmation);

  image8 = gtk_image_new_from_stock ("gtk-caps-lock-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_fixed_put (GTK_FIXED (confirmation), image8, 56, 72);
  gtk_widget_set_size_request (image8, 29, 29);

  label41 = gtk_label_new (_("Are you sure you want to delete this agent?\nThis action is irreversible."));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (confirmation), label41, 48, 56);
  gtk_widget_set_size_request (label41, 400, 65);

  confirm = gtk_button_new ();
  gtk_widget_show (confirm);
  gtk_fixed_put (GTK_FIXED (confirmation), confirm, 64, 168);
  gtk_widget_set_size_request (confirm, 152, 37);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (confirm), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image47 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image47);
  gtk_box_pack_start (GTK_BOX (hbox16), image47, FALSE, FALSE, 0);

  label74 = gtk_label_new_with_mnemonic (_("confirm "));
  gtk_widget_show (label74);
  gtk_box_pack_start (GTK_BOX (hbox16), label74, FALSE, FALSE, 0);

  cancelconfirmation = gtk_button_new ();
  gtk_widget_show (cancelconfirmation);
  gtk_fixed_put (GTK_FIXED (confirmation), cancelconfirmation, 264, 168);
  gtk_widget_set_size_request (cancelconfirmation, 152, 37);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (cancelconfirmation), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image46 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image46);
  gtk_box_pack_start (GTK_BOX (hbox15), image46, FALSE, FALSE, 0);

  label73 = gtk_label_new_with_mnemonic (_("cancel"));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox15), label73, FALSE, FALSE, 0);

  label90 = gtk_label_new ("");
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (confirmation), label90, 416, 224);
  gtk_widget_set_size_request (label90, 49, 17);

  g_signal_connect ((gpointer) confirm, "clicked",
                    G_CALLBACK (on_confirm_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancelconfirmation, "clicked",
                    G_CALLBACK (on_cancelconfirmation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Delete_confirmation, Delete_confirmation, "Delete_confirmation");
  GLADE_HOOKUP_OBJECT (Delete_confirmation, confirmation, "confirmation");
  GLADE_HOOKUP_OBJECT (Delete_confirmation, image8, "image8");
  GLADE_HOOKUP_OBJECT (Delete_confirmation, label41, "label41");
  GLADE_HOOKUP_OBJECT (Delete_confirmation, confirm, "confirm");
  GLADE_HOOKUP_OBJECT (Delete_confirmation, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Delete_confirmation, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Delete_confirmation, image47, "image47");
  GLADE_HOOKUP_OBJECT (Delete_confirmation, label74, "label74");
  GLADE_HOOKUP_OBJECT (Delete_confirmation, cancelconfirmation, "cancelconfirmation");
  GLADE_HOOKUP_OBJECT (Delete_confirmation, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Delete_confirmation, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Delete_confirmation, image46, "image46");
  GLADE_HOOKUP_OBJECT (Delete_confirmation, label73, "label73");
  GLADE_HOOKUP_OBJECT (Delete_confirmation, label90, "label90");

  return Delete_confirmation;
}

GtkWidget*
create_Tache_supplementaire_ (void)
{
  GtkWidget *Tache_supplementaire_;
  GtkWidget *fixed19;
  GtkWidget *treeview2;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *yeartachesupp;
  GtkWidget *daytachesupp;
  GtkWidget *monthtachesupp;
  GtkWidget *Close;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image16;
  GtkWidget *label55;
  GtkWidget *image53;
  GtkWidget *label54;
  GtkWidget *Rechercher;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image48;
  GtkWidget *label77;
  GtkWidget *label91;

  Tache_supplementaire_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Tache_supplementaire_), _("Tache supplementaire"));

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (Tache_supplementaire_), fixed19);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed19), treeview2, 64, 216);
  gtk_widget_set_size_request (treeview2, 392, 152);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed19), spinbutton1, 144, 104);
  gtk_widget_set_size_request (spinbutton1, 48, 27);

  spinbutton3_adj = gtk_adjustment_new (1, 2010, 2024, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed19), spinbutton3, 352, 104);
  gtk_widget_set_size_request (spinbutton3, 64, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed19), spinbutton2, 256, 104);
  gtk_widget_set_size_request (spinbutton2, 48, 27);

  yeartachesupp = gtk_label_new (_("Year:"));
  gtk_widget_show (yeartachesupp);
  gtk_fixed_put (GTK_FIXED (fixed19), yeartachesupp, 304, 112);
  gtk_widget_set_size_request (yeartachesupp, 49, 17);

  daytachesupp = gtk_label_new (_("Day:"));
  gtk_widget_show (daytachesupp);
  gtk_fixed_put (GTK_FIXED (fixed19), daytachesupp, 104, 112);
  gtk_widget_set_size_request (daytachesupp, 49, 17);

  monthtachesupp = gtk_label_new (_("Month:"));
  gtk_widget_show (monthtachesupp);
  gtk_fixed_put (GTK_FIXED (fixed19), monthtachesupp, 200, 112);
  gtk_widget_set_size_request (monthtachesupp, 49, 17);

  Close = gtk_button_new ();
  gtk_widget_show (Close);
  gtk_fixed_put (GTK_FIXED (fixed19), Close, 224, 432);
  gtk_widget_set_size_request (Close, 96, 37);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (Close), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image16 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox1), image16, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("Close"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox1), label55, FALSE, FALSE, 0);

  image53 = create_pixmap (Tache_supplementaire_, "park&go.png");
  gtk_widget_show (image53);
  gtk_fixed_put (GTK_FIXED (fixed19), image53, 400, 8);
  gtk_widget_set_size_request (image53, 117, 72);
  gtk_misc_set_alignment (GTK_MISC (image53), 0.2, 0.5);

  label54 = gtk_label_new (_("Display  citizens Reservations by Date :"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed19), label54, 8, 64);
  gtk_widget_set_size_request (label54, 272, 33);

  Rechercher = gtk_button_new ();
  gtk_widget_show (Rechercher);
  gtk_fixed_put (GTK_FIXED (fixed19), Rechercher, 152, 160);
  gtk_widget_set_size_request (Rechercher, 232, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (Rechercher), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image48 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image48);
  gtk_box_pack_start (GTK_BOX (hbox17), image48, FALSE, FALSE, 0);

  label77 = gtk_label_new_with_mnemonic (_("Research"));
  gtk_widget_show (label77);
  gtk_box_pack_start (GTK_BOX (hbox17), label77, FALSE, FALSE, 0);

  label91 = gtk_label_new ("");
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed19), label91, 472, 480);
  gtk_widget_set_size_request (label91, 49, 17);

  g_signal_connect ((gpointer) Close, "clicked",
                    G_CALLBACK (on_Close_clicked),
                    NULL);
  g_signal_connect ((gpointer) Rechercher, "clicked",
                    G_CALLBACK (on_Rechercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Tache_supplementaire_, Tache_supplementaire_, "Tache_supplementaire_");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, yeartachesupp, "yeartachesupp");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, daytachesupp, "daytachesupp");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, monthtachesupp, "monthtachesupp");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, Close, "Close");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, image16, "image16");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, label55, "label55");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, image53, "image53");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, label54, "label54");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, Rechercher, "Rechercher");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, image48, "image48");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, label77, "label77");
  GLADE_HOOKUP_OBJECT (Tache_supplementaire_, label91, "label91");

  return Tache_supplementaire_;
}

GtkWidget*
create_Success (void)
{
  GtkWidget *Success;
  GtkWidget *fixed20;
  GtkWidget *image22;
  GtkWidget *label60;
  GtkWidget *oksuccess;
  GtkWidget *label93;

  Success = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Success), _("Success"));

  fixed20 = gtk_fixed_new ();
  gtk_widget_show (fixed20);
  gtk_container_add (GTK_CONTAINER (Success), fixed20);

  image22 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed20), image22, 40, 48);
  gtk_widget_set_size_request (image22, 32, 29);

  label60 = gtk_label_new (_("Your task has been completed successfully !"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed20), label60, 56, 40);
  gtk_widget_set_size_request (label60, 328, 48);

  oksuccess = gtk_button_new_with_mnemonic (_("Ok"));
  gtk_widget_show (oksuccess);
  gtk_fixed_put (GTK_FIXED (fixed20), oksuccess, 168, 96);
  gtk_widget_set_size_request (oksuccess, 74, 29);

  label93 = gtk_label_new ("");
  gtk_widget_show (label93);
  gtk_fixed_put (GTK_FIXED (fixed20), label93, 352, 136);
  gtk_widget_set_size_request (label93, 49, 17);

  g_signal_connect ((gpointer) oksuccess, "clicked",
                    G_CALLBACK (on_oksuccess_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Success, Success, "Success");
  GLADE_HOOKUP_OBJECT (Success, fixed20, "fixed20");
  GLADE_HOOKUP_OBJECT (Success, image22, "image22");
  GLADE_HOOKUP_OBJECT (Success, label60, "label60");
  GLADE_HOOKUP_OBJECT (Success, oksuccess, "oksuccess");
  GLADE_HOOKUP_OBJECT (Success, label93, "label93");

  return Success;
}

GtkWidget*
create_Echec (void)
{
  GtkWidget *Echec;
  GtkWidget *fixed21;
  GtkWidget *image23;
  GtkWidget *label61;
  GtkWidget *okoups;
  GtkWidget *label97;

  Echec = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Echec), _("Echec"));

  fixed21 = gtk_fixed_new ();
  gtk_widget_show (fixed21);
  gtk_container_add (GTK_CONTAINER (Echec), fixed21);

  image23 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed21), image23, 56, 72);
  gtk_widget_set_size_request (image23, 48, 37);

  label61 = gtk_label_new (_("Oups! Something went wrong."));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed21), label61, 80, 72);
  gtk_widget_set_size_request (label61, 240, 33);

  okoups = gtk_button_new_with_mnemonic (_("Ok"));
  gtk_widget_show (okoups);
  gtk_fixed_put (GTK_FIXED (fixed21), okoups, 152, 120);
  gtk_widget_set_size_request (okoups, 74, 29);

  label97 = gtk_label_new ("");
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed21), label97, 312, 160);
  gtk_widget_set_size_request (label97, 49, 17);

  g_signal_connect ((gpointer) okoups, "clicked",
                    G_CALLBACK (on_okoups_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Echec, Echec, "Echec");
  GLADE_HOOKUP_OBJECT (Echec, fixed21, "fixed21");
  GLADE_HOOKUP_OBJECT (Echec, image23, "image23");
  GLADE_HOOKUP_OBJECT (Echec, label61, "label61");
  GLADE_HOOKUP_OBJECT (Echec, okoups, "okoups");
  GLADE_HOOKUP_OBJECT (Echec, label97, "label97");

  return Echec;
}

GtkWidget*
create_Gender (void)
{
  GtkWidget *Gender;
  GtkWidget *fixed22;
  GtkWidget *label75;
  GtkWidget *label76;
  GtkWidget *label96;

  Gender = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gender), _("Gender"));

  fixed22 = gtk_fixed_new ();
  gtk_widget_show (fixed22);
  gtk_container_add (GTK_CONTAINER (Gender), fixed22);

  label75 = gtk_label_new (_("Error : No gender selected !"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed22), label75, 104, 72);
  gtk_widget_set_size_request (label75, 184, 33);

  label76 = gtk_label_new (_("You have  to try again."));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed22), label76, 80, 96);
  gtk_widget_set_size_request (label76, 240, 33);

  label96 = gtk_label_new ("");
  gtk_widget_show (label96);
  gtk_fixed_put (GTK_FIXED (fixed22), label96, 336, 160);
  gtk_widget_set_size_request (label96, 49, 17);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gender, Gender, "Gender");
  GLADE_HOOKUP_OBJECT (Gender, fixed22, "fixed22");
  GLADE_HOOKUP_OBJECT (Gender, label75, "label75");
  GLADE_HOOKUP_OBJECT (Gender, label76, "label76");
  GLADE_HOOKUP_OBJECT (Gender, label96, "label96");

  return Gender;
}

GtkWidget*
create_successfull_deletion (void)
{
  GtkWidget *successfull_deletion;
  GtkWidget *fixed23;
  GtkWidget *image54;
  GtkWidget *label79;
  GtkWidget *bye1;
  GtkWidget *image57;
  GtkWidget *label95;

  successfull_deletion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (successfull_deletion), _("successfull_deletion"));

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_container_add (GTK_CONTAINER (successfull_deletion), fixed23);

  image54 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image54);
  gtk_fixed_put (GTK_FIXED (fixed23), image54, 88, 96);
  gtk_widget_set_size_request (image54, 32, 29);

  label79 = gtk_label_new (_("Agent deleted successfully !"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed23), label79, 112, 88);
  gtk_widget_set_size_request (label79, 208, 41);

  bye1 = gtk_button_new ();
  gtk_widget_show (bye1);
  gtk_fixed_put (GTK_FIXED (fixed23), bye1, 360, 8);
  gtk_widget_set_size_request (bye1, 34, 29);

  image57 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image57);
  gtk_container_add (GTK_CONTAINER (bye1), image57);

  label95 = gtk_label_new ("");
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed23), label95, 352, 160);
  gtk_widget_set_size_request (label95, 49, 17);

  g_signal_connect ((gpointer) bye1, "clicked",
                    G_CALLBACK (on_bye1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (successfull_deletion, successfull_deletion, "successfull_deletion");
  GLADE_HOOKUP_OBJECT (successfull_deletion, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (successfull_deletion, image54, "image54");
  GLADE_HOOKUP_OBJECT (successfull_deletion, label79, "label79");
  GLADE_HOOKUP_OBJECT (successfull_deletion, bye1, "bye1");
  GLADE_HOOKUP_OBJECT (successfull_deletion, image57, "image57");
  GLADE_HOOKUP_OBJECT (successfull_deletion, label95, "label95");

  return successfull_deletion;
}

GtkWidget*
create_Agent_not_found (void)
{
  GtkWidget *Agent_not_found;
  GtkWidget *fixed24;
  GtkWidget *image55;
  GtkWidget *label80;
  GtkWidget *bye2;
  GtkWidget *image58;
  GtkWidget *label94;

  Agent_not_found = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Agent_not_found), _("Agent_not_found"));

  fixed24 = gtk_fixed_new ();
  gtk_widget_show (fixed24);
  gtk_container_add (GTK_CONTAINER (Agent_not_found), fixed24);

  image55 = gtk_image_new_from_stock ("gtk-caps-lock-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image55);
  gtk_fixed_put (GTK_FIXED (fixed24), image55, 64, 88);
  gtk_widget_set_size_request (image55, 37, 37);

  label80 = gtk_label_new (_("Agent not found ! Enter a valid NIC ."));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed24), label80, 96, 88);
  gtk_widget_set_size_request (label80, 240, 41);

  bye2 = gtk_button_new ();
  gtk_widget_show (bye2);
  gtk_fixed_put (GTK_FIXED (fixed24), bye2, 368, 8);
  gtk_widget_set_size_request (bye2, 34, 29);

  image58 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image58);
  gtk_container_add (GTK_CONTAINER (bye2), image58);

  label94 = gtk_label_new ("");
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed24), label94, 368, 160);
  gtk_widget_set_size_request (label94, 49, 17);

  g_signal_connect ((gpointer) bye2, "clicked",
                    G_CALLBACK (on_bye2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Agent_not_found, Agent_not_found, "Agent_not_found");
  GLADE_HOOKUP_OBJECT (Agent_not_found, fixed24, "fixed24");
  GLADE_HOOKUP_OBJECT (Agent_not_found, image55, "image55");
  GLADE_HOOKUP_OBJECT (Agent_not_found, label80, "label80");
  GLADE_HOOKUP_OBJECT (Agent_not_found, bye2, "bye2");
  GLADE_HOOKUP_OBJECT (Agent_not_found, image58, "image58");
  GLADE_HOOKUP_OBJECT (Agent_not_found, label94, "label94");

  return Agent_not_found;
}

GtkWidget*
create_Research (void)
{
  GtkWidget *Research;
  GtkWidget *fixed25;
  GtkWidget *entry1;
  GtkWidget *button2;
  GtkWidget *image61;
  GtkWidget *label84;
  GtkWidget *Research2;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image60;
  GtkWidget *label85;
  GtkWidget *label83;
  GtkWidget *image64;
  GtkWidget *label86;
  GtkWidget *label82;

  Research = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Research), _("Research"));

  fixed25 = gtk_fixed_new ();
  gtk_widget_show (fixed25);
  gtk_container_add (GTK_CONTAINER (Research), fixed25);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed25), entry1, 176, 96);
  gtk_widget_set_size_request (entry1, 208, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed25), button2, 8, 8);
  gtk_widget_set_size_request (button2, 40, 29);

  image61 = gtk_image_new_from_stock ("gtk-select-all", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image61);
  gtk_container_add (GTK_CONTAINER (button2), image61);

  label84 = gtk_label_new (_("NIC :"));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed25), label84, 112, 104);
  gtk_widget_set_size_request (label84, 49, 17);

  Research2 = gtk_button_new ();
  gtk_widget_show (Research2);
  gtk_fixed_put (GTK_FIXED (fixed25), Research2, 232, 128);
  gtk_widget_set_size_request (Research2, 96, 29);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (Research2), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image60 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image60);
  gtk_box_pack_start (GTK_BOX (hbox19), image60, FALSE, FALSE, 0);

  label85 = gtk_label_new_with_mnemonic (_("Research"));
  gtk_widget_show (label85);
  gtk_box_pack_start (GTK_BOX (hbox19), label85, FALSE, FALSE, 0);

  label83 = gtk_label_new ("");
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed25), label83, 0, 176);
  gtk_widget_set_size_request (label83, 552, 32);

  image64 = create_pixmap (Research, "park&go.png");
  gtk_widget_show (image64);
  gtk_fixed_put (GTK_FIXED (fixed25), image64, 432, 8);
  gtk_widget_set_size_request (image64, 112, 84);
  gtk_misc_set_alignment (GTK_MISC (image64), 0.2, 0.5);

  label86 = gtk_label_new (_("*********************"));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (fixed25), label86, 88, 168);
  gtk_widget_set_size_request (label86, 400, 136);

  label82 = gtk_label_new (_("Research agent by NIC  :"));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed25), label82, 120, 48);
  gtk_widget_set_size_request (label82, 320, 41);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) Research2, "clicked",
                    G_CALLBACK (on_Research2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Research, Research, "Research");
  GLADE_HOOKUP_OBJECT (Research, fixed25, "fixed25");
  GLADE_HOOKUP_OBJECT (Research, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (Research, button2, "button2");
  GLADE_HOOKUP_OBJECT (Research, image61, "image61");
  GLADE_HOOKUP_OBJECT (Research, label84, "label84");
  GLADE_HOOKUP_OBJECT (Research, Research2, "Research2");
  GLADE_HOOKUP_OBJECT (Research, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Research, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Research, image60, "image60");
  GLADE_HOOKUP_OBJECT (Research, label85, "label85");
  GLADE_HOOKUP_OBJECT (Research, label83, "label83");
  GLADE_HOOKUP_OBJECT (Research, image64, "image64");
  GLADE_HOOKUP_OBJECT (Research, label86, "label86");
  GLADE_HOOKUP_OBJECT (Research, label82, "label82");

  return Research;
}

GtkWidget*
create_admincitoyen (void)
{
  GtkWidget *admincitoyen;
  GtkWidget *fixed169;
  GtkWidget *image144;
  GtkWidget *buttonadministrateur;
  GtkWidget *alignment93;
  GtkWidget *hbox88;
  GtkWidget *image111;
  GtkWidget *label366;
  GtkWidget *buttonanciencitoyen;
  GtkWidget *alignment94;
  GtkWidget *hbox89;
  GtkWidget *image114;
  GtkWidget *label367;
  GtkWidget *label368;
  GtkWidget *buttonnouveaucitoyen;
  GtkWidget *alignment95;
  GtkWidget *hbox90;
  GtkWidget *image115;
  GtkWidget *label369;

  admincitoyen = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (admincitoyen), _("Admin Citoyen"));

  fixed169 = gtk_fixed_new ();
  gtk_widget_show (fixed169);
  gtk_container_add (GTK_CONTAINER (admincitoyen), fixed169);

  image144 = create_pixmap (admincitoyen, "Capture du 2024-10-25 14-28-22.png");
  gtk_widget_show (image144);
  gtk_fixed_put (GTK_FIXED (fixed169), image144, 0, 0);
  gtk_widget_set_size_request (image144, 512, 136);

  buttonadministrateur = gtk_button_new ();
  gtk_widget_show (buttonadministrateur);
  gtk_fixed_put (GTK_FIXED (fixed169), buttonadministrateur, 136, 176);
  gtk_widget_set_size_request (buttonadministrateur, 232, 48);

  alignment93 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment93);
  gtk_container_add (GTK_CONTAINER (buttonadministrateur), alignment93);

  hbox88 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox88);
  gtk_container_add (GTK_CONTAINER (alignment93), hbox88);

  image111 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image111);
  gtk_box_pack_start (GTK_BOX (hbox88), image111, FALSE, FALSE, 0);

  label366 = gtk_label_new_with_mnemonic (_("Administration Section"));
  gtk_widget_show (label366);
  gtk_box_pack_start (GTK_BOX (hbox88), label366, FALSE, FALSE, 0);

  buttonanciencitoyen = gtk_button_new ();
  gtk_widget_show (buttonanciencitoyen);
  gtk_fixed_put (GTK_FIXED (fixed169), buttonanciencitoyen, 24, 248);
  gtk_widget_set_size_request (buttonanciencitoyen, 216, 48);

  alignment94 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment94);
  gtk_container_add (GTK_CONTAINER (buttonanciencitoyen), alignment94);

  hbox89 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox89);
  gtk_container_add (GTK_CONTAINER (alignment94), hbox89);

  image114 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image114);
  gtk_box_pack_start (GTK_BOX (hbox89), image114, FALSE, FALSE, 0);

  label367 = gtk_label_new_with_mnemonic (_("Log in as an existant citizen"));
  gtk_widget_show (label367);
  gtk_box_pack_start (GTK_BOX (hbox89), label367, FALSE, FALSE, 0);

  label368 = gtk_label_new ("");
  gtk_widget_show (label368);
  gtk_fixed_put (GTK_FIXED (fixed169), label368, 384, 304);
  gtk_widget_set_size_request (label368, 120, 40);

  buttonnouveaucitoyen = gtk_button_new ();
  gtk_widget_show (buttonnouveaucitoyen);
  gtk_fixed_put (GTK_FIXED (fixed169), buttonnouveaucitoyen, 280, 248);
  gtk_widget_set_size_request (buttonnouveaucitoyen, 216, 48);

  alignment95 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment95);
  gtk_container_add (GTK_CONTAINER (buttonnouveaucitoyen), alignment95);

  hbox90 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox90);
  gtk_container_add (GTK_CONTAINER (alignment95), hbox90);

  image115 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image115);
  gtk_box_pack_start (GTK_BOX (hbox90), image115, FALSE, FALSE, 0);

  label369 = gtk_label_new_with_mnemonic (_("Log in as new citizen"));
  gtk_widget_show (label369);
  gtk_box_pack_start (GTK_BOX (hbox90), label369, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonadministrateur, "clicked",
                    G_CALLBACK (on_buttonadministrateur_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (admincitoyen, admincitoyen, "admincitoyen");
  GLADE_HOOKUP_OBJECT (admincitoyen, fixed169, "fixed169");
  GLADE_HOOKUP_OBJECT (admincitoyen, image144, "image144");
  GLADE_HOOKUP_OBJECT (admincitoyen, buttonadministrateur, "buttonadministrateur");
  GLADE_HOOKUP_OBJECT (admincitoyen, alignment93, "alignment93");
  GLADE_HOOKUP_OBJECT (admincitoyen, hbox88, "hbox88");
  GLADE_HOOKUP_OBJECT (admincitoyen, image111, "image111");
  GLADE_HOOKUP_OBJECT (admincitoyen, label366, "label366");
  GLADE_HOOKUP_OBJECT (admincitoyen, buttonanciencitoyen, "buttonanciencitoyen");
  GLADE_HOOKUP_OBJECT (admincitoyen, alignment94, "alignment94");
  GLADE_HOOKUP_OBJECT (admincitoyen, hbox89, "hbox89");
  GLADE_HOOKUP_OBJECT (admincitoyen, image114, "image114");
  GLADE_HOOKUP_OBJECT (admincitoyen, label367, "label367");
  GLADE_HOOKUP_OBJECT (admincitoyen, label368, "label368");
  GLADE_HOOKUP_OBJECT (admincitoyen, buttonnouveaucitoyen, "buttonnouveaucitoyen");
  GLADE_HOOKUP_OBJECT (admincitoyen, alignment95, "alignment95");
  GLADE_HOOKUP_OBJECT (admincitoyen, hbox90, "hbox90");
  GLADE_HOOKUP_OBJECT (admincitoyen, image115, "image115");
  GLADE_HOOKUP_OBJECT (admincitoyen, label369, "label369");

  return admincitoyen;
}

GtkWidget*
create_gerer (void)
{
  GtkWidget *gerer;
  GtkWidget *fixed4;
  GtkWidget *image145;
  GtkWidget *label405;
  GtkWidget *buttonagents;
  GtkWidget *buttonservice_gerer;
  GtkWidget *buttonparking;
  GtkWidget *button_retour_ladmincitoyen;
  GtkWidget *alignment110;
  GtkWidget *hbox105;
  GtkWidget *image143;
  GtkWidget *label406;

  gerer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gerer), _("Gestion"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (gerer), fixed4);

  image145 = create_pixmap (gerer, "Capture du 2024-10-25 14-28-22.png");
  gtk_widget_show (image145);
  gtk_fixed_put (GTK_FIXED (fixed4), image145, 0, 0);
  gtk_widget_set_size_request (image145, 528, 136);

  label405 = gtk_label_new ("");
  gtk_widget_show (label405);
  gtk_fixed_put (GTK_FIXED (fixed4), label405, 392, 224);
  gtk_widget_set_size_request (label405, 48, 88);

  buttonagents = gtk_button_new_with_mnemonic (_("Manage Agents "));
  gtk_widget_show (buttonagents);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonagents, 304, 168);
  gtk_widget_set_size_request (buttonagents, 184, 56);

  buttonservice_gerer = gtk_button_new_with_mnemonic (_("Manage Services"));
  gtk_widget_show (buttonservice_gerer);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonservice_gerer, 24, 168);
  gtk_widget_set_size_request (buttonservice_gerer, 184, 56);

  buttonparking = gtk_button_new_with_mnemonic (_("Manage Parkings "));
  gtk_widget_show (buttonparking);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonparking, 168, 240);
  gtk_widget_set_size_request (buttonparking, 184, 56);

  button_retour_ladmincitoyen = gtk_button_new ();
  gtk_widget_show (button_retour_ladmincitoyen);
  gtk_fixed_put (GTK_FIXED (fixed4), button_retour_ladmincitoyen, 456, 272);
  gtk_widget_set_size_request (button_retour_ladmincitoyen, 64, 32);

  alignment110 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment110);
  gtk_container_add (GTK_CONTAINER (button_retour_ladmincitoyen), alignment110);

  hbox105 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox105);
  gtk_container_add (GTK_CONTAINER (alignment110), hbox105);

  image143 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image143);
  gtk_box_pack_start (GTK_BOX (hbox105), image143, FALSE, FALSE, 0);

  label406 = gtk_label_new_with_mnemonic (_("Quit"));
  gtk_widget_show (label406);
  gtk_box_pack_start (GTK_BOX (hbox105), label406, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonagents, "clicked",
                    G_CALLBACK (on_buttonagents_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonservice_gerer, "clicked",
                    G_CALLBACK (on_buttonservice_gerer_clicked),
                    NULL);
  /*g_signal_connect ((gpointer) buttonparking, "clicked",
                    G_CALLBACK (on_buttonparking_clicked),
                    NULL);*/
  g_signal_connect ((gpointer) button_retour_ladmincitoyen, "clicked",
                    G_CALLBACK (on_button_retour_ladmincitoyen_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gerer, gerer, "gerer");
  GLADE_HOOKUP_OBJECT (gerer, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (gerer, image145, "image145");
  GLADE_HOOKUP_OBJECT (gerer, label405, "label405");
  GLADE_HOOKUP_OBJECT (gerer, buttonagents, "buttonagents");
  GLADE_HOOKUP_OBJECT (gerer, buttonservice_gerer, "buttonservice_gerer");
  GLADE_HOOKUP_OBJECT (gerer, buttonparking, "buttonparking");
  GLADE_HOOKUP_OBJECT (gerer, button_retour_ladmincitoyen, "button_retour_ladmincitoyen");
  GLADE_HOOKUP_OBJECT (gerer, alignment110, "alignment110");
  GLADE_HOOKUP_OBJECT (gerer, hbox105, "hbox105");
  GLADE_HOOKUP_OBJECT (gerer, image143, "image143");
  GLADE_HOOKUP_OBJECT (gerer, label406, "label406");

  return gerer;
}

