/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif
#include <gtk/gtk.h>
#include "interface.h"
#include "support.h"


int main(int argc, char *argv[]) {


  //GtkWidget *Add;
  //GtkWidget *Display;
  GtkWidget *admincitoyen;
  /*GtkWidget *Remove;
  GtkWidget *Edit;
  GtkWidget *Confirmation;
  GtkWidget *Delete_confirmation;
  GtkWidget *Tache_supplementaire_;
  GtkWidget *Success;
  GtkWidget *Echec;
  GtkWidget *Gender;
  GtkWidget *successfull_deletion;
  GtkWidget *Agent_not_found;
  */

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

   gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  
   /* The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
  */
    admincitoyen = create_admincitoyen ();
    gtk_widget_show (admincitoyen);
 // Add = create_Add ();
 //gtk_widget_show (Add);
  //Display = create_Display ();
  //gtk_widget_show (Display);
  /*Remove = create_Remove ();
  gtk_widget_show (Remove);
  Edit = create_Edit ();
  gtk_widget_show (Edit);
  Confirmation = create_Confirmation ();
  gtk_widget_show (Confirmation);
  Delete_confirmation = create_Delete_confirmation ();
  gtk_widget_show (Delete_confirmation);
  Tache_supplementaire_ = create_Tache_supplementaire_ ();
  gtk_widget_show (Tache_supplementaire_);
  Success = create_Success ();
  gtk_widget_show (Success);
  Echec = create_Echec ();
  gtk_widget_show (Echec);
  Gender = create_Gender ();
  gtk_widget_show (Gender);
  successfull_deletion = create_successfull_deletion ();
  gtk_widget_show (successfull_deletion);
  Agent_not_found = create_Agent_not_found();
  gtk_widget_show (Agent_not_found);
  */
  gtk_main ();
  return 0;
}


